name: resnet_train
display_name: Train ResNet50 Ensemble Model
version: 1
type: command
description: Train ensemble model (e.g., ResNet50) on disaster damage classification dataset.

inputs:
  train_data:
    type: uri_folder
    description: Folder containing training images
  test_data:
    type: uri_folder
    description: Folder containing test images
  epoch:
    type: integer
    default: 1
  batch_size:
    type: integer
    default: 32
  learning_rate:
    type: number
    default: 0.0001

outputs:
  output_dir:
    type: uri_folder
    description: Folder containing the trained model and predictions

environment: azureml://registries/azureml/environments/acpt-pytorch-2.2-cuda12.1/versions/37

code: .  # This folder contains train_ensemble.py and any needed files

command: >-
  pip install numpy==1.26.4 matplotlib==3.8.2 seaborn==0.13.2
  scikit-learn albumentations tqdm Pillow &&
  python train_ensemble.py
  --train_data ${{inputs.train_data}}
  --test_data ${{inputs.test_data}}
  --epoch ${{inputs.epoch}}
  --batch_size ${{inputs.batch_size}}
  --learning_rate ${{inputs.learning_rate}}
  --output_dir ${{outputs.output_dir}}